### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by KentonParton** [sardetushar/awsglue-pycharm-local-dev#1]
Hello,

I have followed your tutorial but I am running into an error which I am unable to resolve. Instead of downloading your JAR, I built it from the latest version using Java 8 with:

`mvn clean install`

The error I am getting:

```
Traceback (most recent call last):
  File "/projects/glue2/main.py", line 16, in <module>
    glueContext = GlueContext(sc)
  File "/projects/glue2/awsglue/context.py", line 47, in __init__
    self._glue_scala_context = self._get_glue_scala_context(**options)
  File "/projects/glue2/awsglue/context.py", line 68, in _get_glue_scala_context
    return self._jvm.GlueContext(self._jsc.sc())
TypeError: 'JavaPackage' object is not callable
```
Would you mind checking if you are able to build the latest version and run it?

Thanks for your help and time.

**Comment by sardetushar** [comment]
Did you solve it ? sorry I could not contribute much.

Let me know if you still need help.
